# Setting env variables

PATH=$HOME/.local/bin:$home/bin:/bin:/usr/bin:/usr/sbin:/sbin

CPATH=$HOME/.local/lib:/usr/local/lib:/usr/lib:/lib
LIBRARY_PATH=$HOME/.local/lib:/usr/local/lib:/usr/lib:/lib
LD_LIBRARY_PATH=$HOME/.local/lib:/usr/local/lib:/usr/lib:/lib

C_INCLUDE_PATH=$HOME/.local/include:/usr/local/include:/usr/include
CPLUS_INCLUDE_PATH=$HOME/.local/include:/usr/local/include:/usr/include

export VISUAL=vim
export EDITOR="$VISUAL"


# Exporting env variables

export PATH
export CPATH
export LIBRARY_PATH
export LD_LIBRARY_PATH
export C_INCLUDE_PATH

source ~/.zshenv.local
